#!/bin/bash

scriptDir=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)

dataDir="${scriptDir}/data"
backupDir="${scriptDir}/backup"
force=false

order=("log" "fak" "sem" "pre" "stu" "zap" "zna")

pomoc() {
	cat << EOF
pomoooooc
EOF
}

die() {
	echo "$1" >&2
	exit "$2"
}

parseParams() {

	while :; do
		case "${1-}" in
		-f )
			force=true
			shift
			;;
		-d )
			dataDir="${2-}"
			shift
			;;
		-b )
			backupDir="${2-}"
			shift
			;;
		-?*)
			die "neznam: '$1'" 1
			;;
		*) break ;;
		esac
		shift
	done

	if [[ ! -d "$dataDir" ]] && ! mkdir -p "$dataDir"; then
		die "nepodarilo sa vytvorit adresar '${dataDir}'" 1
	fi

	logsFile="${dataDir}/log"

	if [[ ! -f "$logsFile" ]] && ! touch "$logsFile"; then
		die "nepodarilo sa vytvorit subor '${logsFile}'" 1
	fi

	facultiesFile="${dataDir}/fak"

	logMessage="$(date "+%Y-%m-%d %H:%M.%S") $$ ${LOGNAME:-x} $0 $@"
	echo "$logMessage" >> $logsFile

	args=("$@")
	command="${args[0]-}"

	case "$command" in
        "pomoc")

            pomoc
            exit 0
            ;;
            
        "cesta-adresář" | "cesta-adresar")

            if [[ "$#" -gt 1 ]]; then
				die "nadbytecne parametry" 1
			fi

            echo "$dataDir"
            exit 0
            ;;
            
        "smaž-adresář" | "smaz-adresar")

            if [[ "$#" -gt 1 ]]; then
				die "nadbytecne parametry" 1
			fi

            if [[ "$force" != true ]]; then
                die "neni -f" 1
            fi

            rm -rf "$dataDir"
            exit 0
            ;;
            
        "log-výběr" | "log-vyber")

            if [[ "$#" -gt 2 ]]; then
				die "nadbytecne parametry" 1
			fi

            if [[ "$#" -eq 2 ]]; then

                local regex="${args[1]}"

                if ! grep -qE "$regex" "$logsFile"; then
                    die "zadna zhoda" 1
                fi

                grep -E "$regex" "$logsFile"
				
            else
                cat "$logsFile"
            fi

            exit 0
            ;;
            
        "log-poslední" | "log-posledni")

            if [[ "$#" -gt 2 ]]; then
				die "nadbytecne parametry" 1
			fi

            local count=10

            if [[ "$#" -eq 2 ]]; then

                if [[ "${args[1]}" =~ ^[0-9]+$ ]]; then
                    count="${args[1]}"
                else
                    die "musi byt cislo" 1
                fi

            fi
            
            if [[ "$#" -eq 1 ]]; then
                tail -n "$count" "$logsFile" | nl -ba | sort -nr
            else
                tail -n "$count" "$logsFile"
            fi

            exit 0
            ;;

		"fakulta-výpis" | "fakulta-vypis")

            if [[ "$#" -gt 2 ]]; then
				die "nadbytecne parametry" 1
			fi

			if [[ ! -f "$facultiesFile" ]]; then
				die "fakulty nene" 1
			fi

			printf "%-8s | %s\n" "Fakulta" "Název"
			printf "%s\n" "--------------------------"

            if [[ "$#" -eq 2 ]]; then

				local id="${args[1]}"

				local name=$(grep -w "^$id" "$facultiesFile" | cut -d '|' -f 2)

				if [[ -z "$name" ]]; then
					die "fakulta neexistuje" 1
				else
					echo $name
					exit 0
				fi

			else

				while IFS="|" read -r idCol nameCol; do
					printf "%-8s | %s\n" "$idCol" "$nameCol"
				done < <(sort "$facultiesFile")

			fi

			exit 0
			;;

		"fakulta-smaž" | "fakulta-smaz")

            if [[ "$#" -gt 2 ]]; then
				die "nadbytecne parametry" 1
			fi

			if [[ $# -lt 2 ]]; then
                die "chyby id" 1
            fi

			if [[ ! -f "$facultiesFile" ]]; then
				die "fakulty nene" 1
			fi

			local id="${args[1]}"

			if ! grep -q "^${id}|" "$facultiesFile"; then
				die "fakulta neexistuje" 1
			fi

			local tempFile="${dataDir}/tmp"
			touch "$tempFile"

			while IFS='|' read -r idCol nameCol; do
				if [[ "$id" != "$idCol" ]]; then
					echo "${idCol}|${nameCol}" >> "$tempFile"
				fi
			done < "$facultiesFile"

			mv "$tempFile" "$facultiesFile"

			exit 0
			;;

        "fakulta-nová" | "fakulta-nova")

            if [[ "$#" -gt 3 ]]; then
				die "nadbytecne parametry" 1
			fi

			if [[ $# -lt 3 ]]; then
                die "chyby id nebo nazev" 1
            fi

			if [[ ! -f "$facultiesFile" ]] && ! touch "$facultiesFile"; then
				die "nepodarilo sa vytvorit subor '${facultiesFile}'" 1
			fi

			local id="${args[1]}"
			local name="${args[2]}"
			
			if [[ ${#id} -gt 8 ]]; then
				die "id prilis dlouhe" 1
			fi
			
			if grep -q "^${id}|" "$facultiesFile"; then
				die "fakulta jiz existuje" 1
			fi
			
			echo "${id}|${name}" >> "$facultiesFile"

			exit 0
			;;

        "fakulta-název" | "fakulta-nazev")

			# TODO: Nelze smazat fakultu, která je použita v registru semestrů (tato podmínka se kontroluje až v rámci kontroly sekce nastavování semestrů).

            if [[ "$#" -gt 3 ]]; then
				die "nadbytecne parametry" 1
			fi

			if [[ $# -lt 3 ]]; then
                die "chyby id nebo nazev" 1
            fi

			if [[ ! -f "$facultiesFile" ]]; then
				die "fakulty nene" 1
			fi

			local id="${args[1]}"
			local name="${args[2]}"

			if ! grep -q "^${id}|" "$facultiesFile"; then
				die "fakulta neexistuje" 1
			fi

			local tempFile="${dataDir}/tmp"
			touch "$tempFile"

			while IFS='|' read -r idCol nameCol; do
				if [[ "$id" == "$idCol" ]]; then
					echo "${id}|${name}" >> "$tempFile"
				else
					echo "${idCol}|${nameCol}" >> "$tempFile"
				fi
			done < "$facultiesFile"

			mv "$tempFile" "$facultiesFile"

			exit 0
			;;

		"záloha" | "zaloha")

            if [[ "$#" -gt 1 ]]; then
				die "nadbytecne parametry" 1
			fi

			if [[ ! -d "$backupDir" ]] && ! mkdir -p "$backupDir"; then
				die "nepodarilo sa vytvorit adresar '${backupDir}'" 1
			fi

			local backupFile="${backupDir}/$(date '+%Y-%m-%d_%H-%M-%S').tar.gz"
    
			if ! tar -czf "$backupFile" -C "$dataDir" .; then
				die "nepodarilo se vytvorit zalohu" 1
			fi

			exit 0
			;;

		"zálohy" | "zalohy")

            if [[ "$#" -gt 1 ]]; then
				die "nadbytecne parametry" 1
			fi

			if [[ ! -d "$backupDir" ]]; then
				die "zalohy nene" 1
			fi
			
			ls "$backupDir" | sort -r

			exit 0
			;;
			
		"zálohy-smaž" | "zalohy-smaz")

            if [[ "$#" -gt 1 ]]; then
				die "nadbytecne parametry" 1
			fi

			if [[ ! -d "$backupDir" ]]; then
				die "zalohy nene" 1
			fi

			local backups=($(ls "$backupDir" | sort -r))
			
			if [[ "${#backups[@]}" -gt 2 ]]; then
				for backup in "${backups[@]:2}"; do
					rm "${backupDir}/${backup}"
				done
			fi

			exit 0
			;;

		"obnova")

            if [[ "$#" -gt 2 ]]; then
				die "nadbytecne parametry" 1
			fi

			if [[ $# -lt 2 ]]; then
                die "chyby timestamp" 1
            fi

			if [[ ! -d "$backupDir" ]]; then
				die "zalohy nene" 1
			fi

			local backupFile="${args[1]}"

			if [[ ! -f "${backupDir}/${backupFile}" ]]; then
				die "zadana zaloha neexistuje" 1
			fi

			if ! tar -xzf "${backupDir}/${backupFile}" -C "$dataDir"; then
				die "chyba pri obnove" 1
			fi

			exit 0
			;;

		"data-md5")

            if [[ "$#" -gt 2 ]]; then
				die "nadbytecne parametry" 1
			fi

			for fileName in "${order[@]}"; do

				local filePath="${dataDir}/${fileName}" 

				if [[ -f "$filePath" ]]; then
					printf "%-4s %s\n" "$fileName" $(md5sum "$filePath" | cut -d ' ' -f1)
				else
					printf "%-4s %s\n" "$fileName" "d41d8cd98f00b204e9800998ecf8427e"
				fi

			done

			exit 0
			;;

		"data-velikost")

            if [[ "$#" -gt 2 ]]; then
				die "nadbytecne parametry" 1
			fi

			for fileName in "${order[@]}"; do

				local filePath="${dataDir}/${fileName}" 

				if [[ -f "$filePath" ]]; then

					# TODO mozna bude potreba pro IS
					printf "%-4s %s\n" "$fileName" $(stat -c%z "$filePath")
					# printf "%-4s %s\n" "$fileName" $(stat -f%z "$filePath")
				else
					printf "%-4s %s\n" "$fileName" "0"
				fi

			done

			exit 0
			;;

		"data-čas" | "data-cas")

            if [[ "$#" -gt 2 ]]; then
				die "nadbytecne parametry" 1
			fi

			for fileName in "${order[@]}"; do

				local filePath="${dataDir}/${fileName}" 

				if [[ -f "$filePath" ]]; then
					printf "%-4s %s\n" "$fileName" $(stat -c "%y" "$filePath" | cut -d '.' -f1)
				else
					printf "%-4s %s\n" "$fileName" "0000-00-00 00:00:00"
				fi

			done

			exit 0
			;;
					
        *)
            die "neznam prikaz: ${command:-<empty>}"
            ;;
    esac

	exit 0
}

parseParams "$@"

